spring:
  application:
    name: hello-spring-cloud-eureka
  zipkin:
    base-url: htttp://localhost:9411

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defautltZone: http://${eureka.instance.hostname}:${server.port}/eureka/