spring:
  application:
    name: hello-spring-cloud-service-admin
  zipkin:
    base-url: htttp://localhost:9411

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defautltZone: http://localhost:8761/eureka/